###
# curl -X POST --location "http://localhost:9000/admin/doRegister"
#    -H "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGE4Mjg2NDVjNGUyM2ViZDNhZjIzOCIsImlhdCI6MTY3NTMzNzk2NSwiZXhwIjoxNjc2MjAxOTY1fQ.Jwvz7u8PURJhuSBhMtI2b-HH7n27GJvWj-gdb6MguOs"
#    -H "Content-Type: application/json"
#    -d "{
#          \"username\": \"dino\",
#          \"password\": \"1234qwer\",
#          \"isAdmin\": false
#        }"
POST http://localhost:9000/admin/doRegister
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGE4Mjg2NDVjNGUyM2ViZDNhZjIzOCIsImlhdCI6MTY3NTMzNzk2NSwiZXhwIjoxNjc2MjAxOTY1fQ.Jwvz7u8PURJhuSBhMtI2b-HH7n27GJvWj-gdb6MguOs
Content-Type: application/json

{
  "username": "dino",
  "password": "1234qwer",
  "isAdmin": false
}

###
# curl -X POST --location "http://localhost:9000/admin/resetPassword"
#    -H "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGJhYTgyYmNmMDFkNWZkZGIyMThhOSIsImlhdCI6MTY3NTM0MDU0NywiZXhwIjoxNjc2MjA0NTQ3fQ.tJzujSZD-u6oz79MzFPWgj75MInQXwk58CbuEMmfw38"
#    -H "Content-Type: application/json"
#    -d "{
#          \"username\": \"dino\",
#          \"password\": \"31231231231212\"
#        }"
POST http://localhost:9000/admin/resetPassword
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGJhYTgyYmNmMDFkNWZkZGIyMThhOSIsImlhdCI6MTY3NTM0MDU0NywiZXhwIjoxNjc2MjA0NTQ3fQ.tJzujSZD-u6oz79MzFPWgj75MInQXwk58CbuEMmfw38
Content-Type: application/json

{
  "username": "dino",
  "password": "31231231231212"
}

###
