###
# curl -X POST --location "http://localhost:9000/customer/doLogin"
#    -H "Content-Type: application/json"
#    -d "{
#          \"username\": \"admin\",
#          \"password\": \"admin\"
#        }"
POST http://localhost:9000/customer/doLogin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
# curl -X POST --location "http://localhost:9000/customer/getUserInfo"
#    -H "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGE4Mjg2NDVjNGUyM2ViZDNhZjIzOCIsImlhdCI6MTY3NTI2NzI2MCwiZXhwIjoxNjc2MTMxMjYwfQ.b_JH2Pu4EJVaKWXDVxPtyXJf41sTCu74c_TCYXpDLKw"
POST http://localhost:9000/customer/getUserInfo
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGE4Mjg2NDVjNGUyM2ViZDNhZjIzOCIsImlhdCI6MTY3NTI2NzI2MCwiZXhwIjoxNjc2MTMxMjYwfQ.b_JH2Pu4EJVaKWXDVxPtyXJf41sTCu74c_TCYXpDLKw

###
